server:
  port: 8081

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/onlinelearn?serverTimezone=UTC
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379

